name: Docker Image CI

on:
  push:
    branches: [main]
jobs:
  build:
    name: ClienteService
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      
      - name: Setup .NET 6
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
          
      - name: Restore dependencies
        run: dotnet restore ClienteService/ClienteService.csproj
      
      - name: Build
        run: dotnet build ClienteService/ClienteService.csproj --no-restore
      
      - name: Login to Docker Hub
        run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker build container image
        run: docker build -t guilhermesav/cliente-service:$(date +%y%m%d).$(git rev-parse --short "$GITHUB_SHA") .
        
      - name: Push to Docker Hub
        run: docker push -a  guilhermesav/cliente-service
